[package]
name = "cargo-package-info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.9"
colored = "2.0.0"

[dependencies.serde]
version = "1.0.140"
features = ["derive"]
optional = true

[features]
default = ["serde"]
