[package]
name = "cargo-package-info"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
indexmap = "1.9.1"
toml = "0.5.9"

[dependencies.serde]
version = "1.0.140"
features = ["derive"]
optional = true

[features]
default = ["serde"]
