[build]
rustflags = ["-D", "clippy::all",
             "-D", "clippy::pedantic",
             "-D", "clippy::correctness",
             "-D", "clippy::suspicious",
             "-D", "clippy::style",
             "-D", "clippy::complexity",
             "-D", "clippy::perf",
             "-A", "clippy::module-name-repetitions"
             ]
